#!/bin/sh
cat header.c > langsel_mac.c
cat langsel.English.mac.c >> langsel_mac.c
echo "" >> langsel_mac.c
cat langsel.Spanish.mac.c >> langsel_mac.c
echo "" >> langsel_mac.c
cat langsel.Italian.mac.c >> langsel_mac.c
echo "" >> langsel_mac.c
cat langsel.French.mac.c >> langsel_mac.c
echo "" >> langsel_mac.c
cat langsel.Russian.mac.c >> langsel_mac.c
echo "" >> langsel_mac.c
cat langsel.Bulgarian.mac.c >> langsel_mac.c
echo "" >> langsel_mac.c
cat langsel.Chinese.mac.c >> langsel_mac.c
echo "" >> langsel_mac.c
cat langsel.Japanese.mac.c >> langsel_mac.c
cat footer.c >> langsel_mac.c
