#!/bin/sh
cat header.utf.c > langsel_utf.c
cat langsel.English.utf.c >> langsel_utf.c
echo "" >> langsel_utf.c
cat langsel.Spanish.utf.c >> langsel_utf.c
echo "" >> langsel_utf.c
cat langsel.Italian.utf.c >> langsel_utf.c
echo "" >> langsel_utf.c
cat langsel.French.utf.c >> langsel_utf.c
echo "" >> langsel_utf.c
cat langsel.Russian.utf.c >> langsel_utf.c
echo "" >> langsel_utf.c
cat langsel.Bulgarian.utf.c >> langsel_utf.c
echo "" >> langsel_utf.c
cat langsel.Chinese.utf.c >> langsel_utf.c
echo "" >> langsel_utf.c
cat langsel.Japanese.utf.c >> langsel_utf.c
cat footer.utf.c >> langsel_utf.c
