#!/bin/sh
cat header.c > langsel_mswin.c
cat langsel.English.c >> langsel_mswin.c
echo "" >> langsel_mswin.c
cat langsel.Spanish.c >> langsel_mswin.c
echo "" >> langsel_mswin.c
cat langsel.Italian.c >> langsel_mswin.c
echo "" >> langsel_mswin.c
cat langsel.French.c >> langsel_mswin.c
echo "" >> langsel_mswin.c
cat langsel.Russian.c >> langsel_mswin.c
echo "" >> langsel_mswin.c
cat langsel.Bulgarian.c >> langsel_mswin.c
echo "" >> langsel_mswin.c
cat langsel.Chinese.c >> langsel_mswin.c
echo "" >> langsel_mswin.c
cat langsel.Japanese.c >> langsel_mswin.c
cat footer.c >> langsel_mswin.c
