#!/bin/sh
cat header.c > langsel_unix.c
cat langsel.English.c >> langsel_unix.c
echo "" >> langsel_unix.c
cat langsel.Spanish.c >> langsel_unix.c
echo "" >> langsel_unix.c
cat langsel.Italian.c >> langsel_unix.c
echo "" >> langsel_unix.c
cat langsel.French.c >> langsel_unix.c
echo "" >> langsel_unix.c
cat langsel.Russian.c >> langsel_unix.c
echo "" >> langsel_unix.c
cat langsel.Bulgarian.c >> langsel_unix.c
echo "" >> langsel_unix.c
cat langsel.Chinese.c >> langsel_unix.c
echo "" >> langsel_unix.c
cat langsel.Japanese.EUC.c >> langsel_unix.c
cat footer.c >> langsel_unix.c
